// dash/components/KpiCard.vue
<script setup lang="ts">
const props = defineProps<{
  label: string;
  value: number | string;
  previousValue?: number;
  suffix?: string;
  color?: string;
  subtitle?: string;
}>();

const displayValue = ref(typeof props.value === 'number' ? 0 : props.value);
const flashing = ref(false);

watch(() => props.value, (val) => {
  if (typeof val === 'number') {
    const from = typeof displayValue.value === 'number' ? displayValue.value : 0;
    const to = val;
    if (from === to) return;
    flashing.value = true;
    setTimeout(() => flashing.value = false, 400);
    const steps = 14;
    const inc = (to - from) / steps;
    let step = 0;
    const t = setInterval(() => {
      step++;
      if (step >= steps) { displayValue.value = to; clearInterval(t); }
      else displayValue.value = Math.round(from + inc * step);
    }, 25);
  } else {
    displayValue.value = val;
  }
}, { immediate: true });

const delta = computed(() => {
  if (props.previousValue === undefined || typeof props.value !== 'number') return 0;
  return props.value - props.previousValue;
});

const pct = computed(() => {
  if (!props.previousValue || props.previousValue <= 0 || typeof props.value !== 'number') return null;
  return (((props.value - props.previousValue) / props.previousValue) * 100).toFixed(1);
});

const colorVar = computed(() => `var(--color-${props.color ?? 'green'})`);
</script>

<template>
  <div class="card px-5 py-4 group">
    <p class="text-[11px] font-medium text-txt-3 uppercase tracking-wider mb-2">{{ label }}</p>
    <p
      class="font-display text-[26px] font-bold tabular leading-none tracking-tight transition-colors duration-300"
      :style="{ color: colorVar }"
      :class="flashing ? 'brightness-150' : ''"
    >
      {{ typeof displayValue === 'number' ? displayValue.toLocaleString('pt-BR') : displayValue }}{{ suffix ?? '' }}
    </p>
    <div class="mt-2 flex items-center gap-2">
      <span
        v-if="delta !== 0 && pct"
        class="inline-flex items-center gap-0.5 text-[10px] font-mono font-medium tabular px-1.5 py-0.5 rounded"
        :style="{
          background: delta > 0 ? 'rgba(74,222,128,0.08)' : 'rgba(239,68,68,0.08)',
          color: delta > 0 ? 'var(--color-green)' : 'var(--color-red)',
        }"
      >
        {{ delta > 0 ? '+' : '' }}{{ pct }}%
      </span>
      <span v-if="subtitle" class="text-[10px] text-txt-3">{{ subtitle }}</span>
    </div>
  </div>
</template>

// dashboard/src/lib/components/KpiCard.svelte
<script lang="ts">
	let {
		label,
		value,
		previousValue = undefined,
		suffix = '',
		color = 'accent',
		subtitle = ''
	}: {
		label: string;
		value: number | string;
		previousValue?: number;
		suffix?: string;
		color?: string;
		subtitle?: string;
	} = $props();

	let displayValue = $state(typeof value === 'number' ? 0 : value);
	let changed = $state(false);

	$effect(() => {
		if (typeof value === 'number') {
			const target = value;
			const current = typeof displayValue === 'number' ? displayValue : 0;
			const diff = target - current;
			if (diff === 0) return;

			changed = true;
			setTimeout(() => (changed = false), 500);

			const steps = 16;
			const increment = diff / steps;
			let step = 0;
			const timer = setInterval(() => {
				step++;
				if (step >= steps) {
					displayValue = target;
					clearInterval(timer);
				} else {
					displayValue = Math.round(current + increment * step);
				}
			}, 30);
			return () => clearInterval(timer);
		} else {
			displayValue = value;
		}
	});

	const delta = $derived(
		previousValue !== undefined && typeof value === 'number' ? value - previousValue : 0
	);

	const deltaPercent = $derived(
		previousValue && previousValue > 0 && typeof value === 'number'
			? (((value - previousValue) / previousValue) * 100).toFixed(1)
			: null
	);
</script>

<div class="card group">
	<div class="flex items-center justify-between mb-1">
		<span class="text-[12px] font-medium text-text-muted">{label}</span>
	</div>

	<div class="flex items-baseline gap-1.5">
		<span
			class="text-2xl font-extrabold tabular-nums leading-none tracking-tight"
			class:flash={changed}
			style="color: var(--color-{color});"
		>
			{typeof displayValue === 'number' ? displayValue.toLocaleString('pt-BR') : displayValue}{suffix}
		</span>
	</div>

	<div class="mt-2 flex items-center gap-2">
		{#if delta !== 0 && deltaPercent}
			<span
				class="inline-flex items-center gap-0.5 text-[11px] font-medium tabular-nums px-1.5 py-0.5 rounded-md"
				style="background: {delta > 0 ? 'rgba(74,222,128,0.1)' : 'rgba(248,113,113,0.1)'}; color: {delta > 0 ? 'var(--color-accent)' : 'var(--color-danger)'};"
			>
				{#if delta > 0}
					<svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M7 17l5-5 5 5M7 7l5 5 5-5"/></svg>
				{/if}
				{deltaPercent}%
			</span>
		{/if}
		{#if subtitle}
			<span class="text-[11px] text-text-muted">{subtitle}</span>
		{/if}
	</div>
</div>
